swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /persona/GuardarPersona:
    post:
      tags:
      - persona
      description: Guardar Persona
      operationId: PersonaController.PostPersona
      parameters:
      - in: body
        name: body
        description: body for Guardar Persona content
        required: true
        schema:
          $ref: '#/definitions/models.PersonaCompleta'
      responses:
        "200":
          description: '{string} models.Persona.Id'
        "403":
          description: body is empty
definitions:
  models.EstadoCivil:
    title: EstadoCivil
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.Genero:
    title: Genero
    type: object
    properties:
      Activo:
        type: boolean
      CodigoAbreviacion:
        type: string
      Descripcion:
        type: string
      Id:
        type: integer
        format: int64
      Nombre:
        type: string
      NumeroOrden:
        type: number
        format: double
  models.PersonaCompleta:
    title: PersonaCompleta
    type: object
    properties:
      Ente:
        type: integer
        format: int64
      EstadoCivil:
        $ref: '#/definitions/models.EstadoCivil'
      FechaNacimiento:
        type: string
        format: string
      Foto:
        type: string
      Genero:
        $ref: '#/definitions/models.Genero'
      Id:
        type: integer
        format: int64
      PrimerApellido:
        type: string
      PrimerNombre:
        type: string
      SegundoApellido:
        type: string
      SegundoNombre:
        type: string
      Usuario:
        type: string
tags:
- name: persona
  description: |
    PersonaController ...
