swagger: "2.0"
info:
  title: beego Test API
  description: beego has a very cool tools to autogenerate documents for your API
  version: 1.0.0
  termsOfService: http://beego.me/
  contact:
    email: astaxie@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
basePath: /v1
paths:
  /persona/ActualizarDatosContacto:
    put:
      tags:
      - persona
      description: Actualizar Datos de Contacto
      operationId: PersonaController.ActualizarDatosContacto
      parameters:
      - in: body
        name: body
        description: body for Actualizar Persona content
        required: true
        schema:
          $ref: '#/definitions/.PersonaDatosBasicos'
      responses:
        "200":
          description: '{string} models.Persona.Id'
        "403":
          description: body is empty
  /persona/ActualizarPersona:
    put:
      tags:
      - persona
      description: Actualizar Persona
      operationId: PersonaController.ActualizarPersona
      parameters:
      - in: body
        name: body
        description: body for Actualizar Persona content
        required: true
        schema:
          $ref: '#/definitions/.PersonaDatosBasicos'
      responses:
        "200":
          description: '{string} models.Persona.Id'
        "403":
          description: body is empty
  /persona/GuardarDatosContacto:
    post:
      tags:
      - persona
      description: Guardar Datos de Contacto
      operationId: PersonaController.PostDatosContacto
      parameters:
      - in: body
        name: body
        description: body for Guardar Persona content
        required: true
        schema:
          $ref: '#/definitions/.PersonaDatosBasicos'
      responses:
        "200":
          description: '{string} models.Persona.Id'
        "403":
          description: body is empty
  /persona/GuardarPersona:
    post:
      tags:
      - persona
      description: Guardar Persona
      operationId: PersonaController.PostPersona
      parameters:
      - in: body
        name: body
        description: body for Guardar Persona content
        required: true
        schema:
          $ref: '#/definitions/.PersonaDatosBasicos'
      responses:
        "200":
          description: '{string} models.Persona.Id'
        "403":
          description: body is empty
definitions:
  .PersonaDatosBasicos:
    type: object
tags:
- name: persona
  description: |
    PersonaController ...
